### ISSUE TITLE
1.2.0 breaks ansible tss lookup plugin

### ISSUE THREAD

**Issue by tomreeb** [DelineaXPM/python-tss-sdk#9]
Since 1.2.0 was released, the Ansible Lookup Plugin, `community.general.tss`, no longer works. When running a previously working (with 1.1.0) playbook I receive the following error:

```
TASK [lookup value for ansible_user] *******************************************
task path: /__w/54/s/big_switch_backup.yml:11
exception during Jinja2 execution: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ansible/template/__init__.py", line 1032, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ansible_collections/community/general/plugins/lookup/tss.py", line 271, in run
    raise AnsibleError("python-tss-sdk must be installed to use this plugin")
ansible.errors.AnsibleError: python-tss-sdk must be installed to use this plugin
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '{{ lookup('community.general.tss', 27318) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'community.general.tss'. Error was a <class 'ansible.errors.AnsibleError'>, original message: python-tss-sdk must be installed to use this plugin. python-tss-sdk must be installed to use this plugin"
}
```

**Comment by tylerezimmerman** [comment]
@tomreeb we believe we have located the issue and are working on a fix. Will update this thread with more info once we run some tests.

**Comment by tomreeb** [comment]
Thanks @tylerezimmerman!  I've submitted https://github.com/ansible-collections/community.general/pull/5151 to fix this.

**Comment by tylerezimmerman** [comment]
@tomreeb thanks for your help on this! Looks like your code was merged in https://github.com/ansible-collections/community.general/pull/5151. Can this issue be considered Resolved?

**Comment by tomreeb** [comment]
Yes this is now resolved. Thank you for your support!
